### ISSUE TITLE
Incoming transactions of LTC and Dash are not shown in the portfolio transaction history page

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/atomicDEX#71] opened 2019-08-05 13:59 UTC
Example:

![IMG_1566](https://user-images.githubusercontent.com/21151592/62469764-95670b80-b7b6-11e9-8e4f-9b184dc8dd4c.jpeg)

The tx history for the same address in Verus Agama:

<img width="1178" alt="Screenshot_2019-08-05_at_11 43 37" src="https://user-images.githubusercontent.com/21151592/62469964-f42c8500-b7b6-11e9-8428-d31b52034abc.png">

the user claims a similar issue is faced in VerusPay mobile and Chainzilla Chameleon for the Dash address.

**Comment by tonymorony** [comment] 2019-08-05 22:47
Thank you for report, will try to reproduce

**Comment by tonymorony** [comment] 2019-08-12 02:14
@gcharang from your screenshots it looks like that only transactions to "self" address not displaying. Could you please confirm that? 
Also can you please send DASH transaction to self from AtomicDEX and from Agama and compare results in AtomicDEX tx history?

Just tried to send few DASH txs to self address in AtomicDEX and it displaying fine. (tx to self displaying as fee consumption) Maybe txs from Agama has some specific.

**Comment by tonymorony** [comment] 2019-09-06 14:09
Closing this one - not able to reproduce

**Closed by tonymorony** 2019-09-06 14:09 UTC
Labels: bug, question
