### ISSUE TITLE
Unlock Funds not possible

### ISSUE THREAD

**Issue by bitwin45** [KomodoPlatform/atomicDEX#135] opened 2020-02-11 17:53 UTC
Hi,

I can‘t unlock my funds after a swap timeout.
OS. Android,  atomicdex 0.2.13
By pushing unlock Button, I get a weird Info
![DE035C20-D8F3-4119-B902-3FB999962BE3](https://user-images.githubusercontent.com/60938066/74263780-c2651f80-4cff-11ea-92d5-a435c7abd0a0.jpeg)

**Comment by tonymorony** [comment] 2020-02-11 19:01
Hello and thank you for issue creation!

 Could you please DM full swaps UUIDs and application log (Settings -> Send log) to my Discord account on https://komodoplatform.com/discord server : @TonyL (272003866906722306) to find out why recovery message parsing like this. Most probably you'll need to wait till the next patch because bigger tx fee is needed for refund as well:
after RVN hardfork txfee was increased 10 times, otherwise transactions rejecting with `the transaction was rejected by network rules. min relay fee not met ` (https://github.com/jl777/coins/pull/420) but this change is not in AtomicDEX mobile yet so please wait till the next patch before trade RVN.

**Comment by bitwin45** [comment] 2020-02-11 19:39
Thx for quick response,
Need Discord Acount first, most probably tomorrow, 
...( wait before next RVN trade) yes, Sending  RVN also not longer possible ... message: Try again later!
cu

**Comment by ArtemGr** [comment] 2020-02-11 23:19
Seen this error before but couldn't reproduce (e.g. after a few attempts this particular error message went away).

**Comment by tonymorony** [comment] 2020-05-23 19:40
This one should be fixed

**Closed as completed by tonymorony** 2020-05-23 19:40 UTC
