### ISSUE TITLE
Unlock Funds ETH to KMD

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#98] opened 2019-10-01 12:18 UTC
Android 
AtomicDEX 0.2.0

After clicking unlock funds the display is "KMD unlocked" or something like that but.. the coins i am unlocking is ETH

**Comment by tonymorony** [comment] 2019-10-05 09:05
Can you provide swap UUID and app log after unlock if possible?

**Comment by dudezmobi** [comment] 2019-10-05 12:19
ffd535b6-dc49-48d5-b72b-388b6af139a1

Cannot export log in discord. I dont have nitro so my file size is limited. Log is already very big.

**Comment by dth88** [comment] 2020-06-01 00:25
@tonymorony I guess we resolved it last year, right?

**Comment by dth88** [comment] 2020-06-03 10:04
closing this one since @dudezmobi replied that the problem is no longer relevant.

**Closed by dth88** 2020-06-03 10:04 UTC
Labels: not enough info
