### ISSUE TITLE
Failed swap causing to Lock funds

### ISSUE THREAD

**Issue by dudezmobi** [KomodoPlatform/atomicDEX#99] opened 2019-10-01 12:20 UTC
Android
AtomicDex 0.2.0

During STEP 2 of SWAPPING, i switched applications and noticed my internet/wifi connection was transferred to a slower bandwidth after this my trade failed and funds locked

**Comment by dudezmobi** [comment] 2019-10-04 21:45
Seems to be happening more often on ETH trades (RICK and MORTY, KMD and VERUS never happened)

**Comment by tonymorony** [comment] 2019-10-05 09:06
Can you provide swaps uuid(s) and app logs? For now from issue description it's not clear what exactly problem is.

**Comment by dudezmobi** [comment] 2019-10-05 12:24
Please coordinate with otherr members gcharang as we have discussed the issue in detail. 019878b2-04a0-4772-8014-913633dbd8d1
ffd535b6-dc49-48d5-b72b-388b6af139a1
 Also it would be much better to have info the soonest possible its logged. Already 4 days ago. Did a lot of thingz on that time frame so you wont be getting good info from a user

**Comment by dth88** [comment] 2020-06-01 00:23
@tonymorony did we reach an end to this one? should I pick it up from here or was it already resolved last year?

**Comment by dth88** [comment] 2020-06-03 10:04
closing this one since @dudezmobi replied that the problem is no longer relevant.

**Closed by dth88** 2020-06-03 10:04 UTC
Labels: not enough info
