### ISSUE TITLE
Message says there are no orders available even though there are some

### ISSUE THREAD

**Issue by gcharang** [KomodoPlatform/atomicDEX#68] opened 2019-08-03 10:11 UTC
Steps to reproduce:

- Go to Trade screen
- Select a coin and set amount
- Select the other coin to trade
- If there are orders available, they are displayed
- select the option "Click to create an order"
- user is taken back to the trade screen, but the message shown below the "Receive" section says: "No '<second coin>' orders available - please try again later, or create an order"

![photo6210530922449709294](https://user-images.githubusercontent.com/21151592/62410593-29917100-b605-11e9-9d0e-1c2765679d03.jpg)

**Comment by ca333** [comment] 2019-08-04 09:57
not able to reproduce - neither on the old nor on the new 0.1.51
@tonymorony can you plz try to reproduce

**Comment by tonymorony** [comment] 2019-08-04 10:15
@ca333 I have same screen as on screenshot on my side, I wonder this issue clue is not precise message: after `"Click to create an order"` option usage it's better to print something like a "Input amount of BTC you want to get" below the "Receive" section so for user will be clear that "Trade" button will became active after BTC amount input

**Comment by tonymorony** [comment] 2019-08-04 10:18
But in general I can not understand how 

> select the option "Click to create an order"

correlates with issue name

**Comment by tonymorony** [comment] 2019-08-05 07:51
Was fixed in 0.1.52

**Closed by tonymorony** 2019-08-05 07:51 UTC
Labels: enhancement
