### ISSUE TITLE
[User experience]: Set up a delay after return of background for pin/fingerprint

### ISSUE THREAD

**Issue by Milerius** [KomodoPlatform/atomicDEX#29] opened 2019-07-19 09:06 UTC
When we go back to the application when it was in background. We should put a delay before asking for the fingerprint or pin code again.

Tested on: **Android**

Version: 0.1.3

Possible duplicate of #21

**Comment by tonymorony** [comment] 2019-07-19 09:50
Thank you for request :+1: But yes, closed as duplicate of https://github.com/KomodoPlatform/atomicDEX/issues/21

**Closed by tonymorony** 2019-07-19 09:50 UTC
