### ISSUE TITLE
[UX] Swap the whole wallet balance

### ISSUE THREAD

**Issue by jorisvial** [KomodoPlatform/atomicDEX#4] opened 2019-07-16 05:39 UTC
It would be nice to have a button allowing to swap the whole balance, to avoid having leftover dust. 
Could be similar to Binance withdrawal "Max" button.

![20190716_143352](https://user-images.githubusercontent.com/9780671/61268636-011d1080-a7d7-11e9-9615-fb1234e35f8a.jpg)
![20190716_143750](https://user-images.githubusercontent.com/9780671/61268757-6ec93c80-a7d7-11e9-995a-aa5ed05ff747.jpg)

**Comment by cipig** [comment] 2019-07-16 05:58
API does support this, eg
```curl --url "http://127.0.0.1:7783" --data "{\"userpass\":\"$userpass\",\"method\":\"withdraw\",\"coin\":\"KMD\",\"to\":\"RT9MpMyucqXiX8bZLimXBnrrn2ofmdGNKd\",\"max\":true}"```
to withdraw all KMD to `RT9MpMyucqXiX8bZLimXBnrrn2ofmdGNKd`

**Comment by Kiruel** [comment] 2019-07-16 08:57
If you enter more than your balance the input should be filed by the max balance you have.

**Comment by jorisvial** [comment] 2019-07-16 09:01
> 
> 
> If you enter more than your balance the input should be filed by the max balance you have.

That's correct. This should be easy to add in this case. Otherwise, would be nice to add this to a potential future UX tutorial (when running the app for the first time).

**Comment by Kiruel** [comment] 2019-07-16 09:06
It's noted in the main project. So i close it here.

**Comment by tonymorony** [comment] 2019-07-19 09:56
needs to be tested in next release

**Comment by tonymorony** [comment] 2019-07-20 14:38
"max" feature was added in 0.1.3-a

**Comment by tonymorony** [comment] 2019-07-20 14:50
the max button doesn't appear (until coin is selected on the DEX page) if on the portfolio list we hover and select swap

![hover](https://user-images.githubusercontent.com/24797699/61580092-89bce900-ab16-11e9-93e3-3e367a88d2d5.jpg)
![nomax](https://user-images.githubusercontent.com/24797699/61580100-af49f280-ab16-11e9-8e3d-57506af74f04.jpg)

**Comment by smk762** [comment] 2019-07-22 10:16
confirmed working MAX button for both send and swap on android with v0.1.3-a db6ded6ec

**Comment by tonymorony** [comment] 2019-07-22 10:17
it's working yes, but not displaying if navigate from hover (described in message above)

**Comment by tonymorony** [comment] 2019-07-26 09:08
Duplicate of #45 
and #45 have more relevant description at the moment so closing

**Closed by tonymorony** 2019-07-26 09:08 UTC
Labels: enhancement
